services:
  web:
    build: ./echo-chamber-web
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
      - "5678:5678"
    environment:
      - PYDEVD_DISABLE_FILE_VALIDATION=1