services:
  echo_db:
    image: postgres:17.3
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - backend

  redis:
    image: redis:alpine
    networks:
      - backend

  echo_web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - echo_db
      - redis
    networks:
      - backend

  celery:
    build: .
    command: celery -A echochamber worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - echo_db
      - redis
    networks:
      - backend

networks:
  backend:
    driver: bridge
